#!/bin/bash -xe

RELEASED_SIMULATORS="CMP.L2Shared.Trace CMP.L2SharedNUCA.OoO CMP.MT4.L2Shared.Trace CMP.MT4.L2SharedNUCA.OoO UP.Trace UP.OoO CMP.L2SharedNUCA.DRAMSim.OoO"
DEST=../release

copy_dir () {
	DIR=$1
	PERM="! -perm -u=x"
	if [ "$2" = "NO_PERM_CHECK" ]; then
		PERM=""
	fi
	find $DIR -name .svn -prune -false -o \! -name .svn -type d -exec mkdir -p "$DEST/{}" \;
	find $DIR -name .svn -prune -false -o \! -name .svn -type f $PERM \! \( -name \*_gcc_o -o -name \*_gcc_dep -o -name \*_gcc -o -name \*.stats_o -o -name \*_gcc.so -o -name \*.depend.v9_iface_gcc -o -name \*.a -o -name \*.a.fresh -o -name \*.rom -o -name \*.mcd_lnk -o -name he.ps -o -name re.ps -o -name he.lst -o -name re.lst \) -exec cp '{}' "$DEST/{}" \;
}

rm -rf $DEST
mkdir -p $DEST
cp Makefile makefile.* DOCUMENTATION $DEST
copy_dir core 
copy_dir doc
copy_dir flexus-test-app
copy_dir stat-manager
copy_dir configs
rm -rf $DEST/configs/old_releases
copy_dir scripts NO_PERM_CHECK

#Make sure none of the simulator files have the permission x.
for i in $RELEASED_SIMULATORS; do
	copy_dir simulators/$i
	RELEASED_COMPONENTS="$RELEASED_COMPONENTS`grep REQUIRED_COMPONENTS simulators/$i/Makefile.$i | cut -d= -f2-`"
done

# Note: newline in "tr" is intentional
RELEASED_COMPONENTS=`echo $RELEASED_COMPONENTS | tr ' ' '
' | sort | uniq`

for i in $RELEASED_COMPONENTS; do
	copy_dir components/$i
done

sed -i'' -e "/CMU-ONLY-BLOCK-BEGIN/,/CMU-ONLY-BLOCK-END/d" -e "/CMU-ONLY/d" `find $DEST -name "*.hpp" -o -name "*.cpp"`

####### insert copyright #######

set +o xtrace
print_header () {
  FILE=$1
  SYM=$2
  echo "$SYM DO-NOT-REMOVE begin-copyright-block ">  $FILE
	sed -e "s!^!$SYM!" cmu-copyright >> $FILE
  echo "$SYM DO-NOT-REMOVE end-copyright-block   ">> $FILE
}

# various comment styles
CPPSTYLE="//"
HASHSTYLE="#"

# applies or updates copyright
apply_header ()
{
  FILE=$1
  SYMBOL=$2
  sed -e '/begin-copyright-block/,/end-copyright-block/d' $FILE > /tmp/$USER-copyright-temp
	echo -n > $FILE
  print_header $FILE $SYMBOL
  cat /tmp/$USER-copyright-temp >> $FILE
}

# look through all c++-related files that belong to us
FILES=`find $DEST -name .svn -prune -false -o -name "*.hpp" -o -name "*.cpp" | grep -v DRAMSim2`
for file in $FILES; do
  apply_header $file $CPPSTYLE
done

FILES=`find $DEST -name .svn -prune -false -o -name "*akefile*"`
for file in $FILES; do
  apply_header $file $HASHSTYLE
done
