# Octopus Simulator build description

#Currently WhiteBox is removed from wiring
REQUIRED_COMPONENTS = CommonQEMU uFetch armDecoder uArchARM FetchAddressGenerate Cache MemoryLoopback MemoryMap MagicBreakQEMU CMPCache MultiNic NetShim TraceTrackerQEMU MTManager SplitDestinationMapper MMU

SUPPORTS_STANDALONE = false
SUPPORTS_SIMICS = false
SUPPORTS_QEMU = true
DEFAULT_TARGET = qemu
SUPPORTS_X86 = false
SUPPORTS_V9 = false
SUPPORTS_ARM = true
DEFAULT_PLATFORM = arm
