# ref: https://stackoverflow.com/questions/7787823/cmake-how-to-get-the-name-of-all-subdirectories-of-a-directory
MACRO(subdirlist result curdir)
        FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
        SET(dirlist "")
	FOREACH(child ${children})
                IF(IS_DIRECTORY ${curdir}/${child})
                        LIST(APPEND dirlist ${child})
                ENDIF()
        ENDFOREACH()
        SET(${result} ${dirlist})
ENDMACRO()   
