# Defines and rules that are the same for all ccs

include $(FLEXUS_ROOT)/makefile.variant

.PHONY: test

.SUFFIXES:
.SUFFIXES: .cpp .$(OEXT) .$(BOOST_OEXT)

include Makefile.depend.$(VARIANT)

test: test/core-test.$(VARIANT_EXT)
	echo "Running core regression tests for $(VARIANT)"
	test/core-test.$(VARIANT_EXT)
