#define FLEXUS_BEGIN_COMPONENT DGP
#include FLEXUS_BEGIN_COMPONENT_DECLARATION()

#define DGP_IMPLEMENTATION (<components/DGP/DGPImpl.hpp>)

#include FLEXUS_END_COMPONENT_DECLARATION()
#define FLEXUS_END_COMPONENT DGP
