# Octopus Simulator build description

REQUIRED_COMPONENTS = Common BPWarm InorderSimicsFeeder Cache MemoryLoopback MemoryMap MagicBreak IFetch Execute LocalEngine ProtocolEngine Directory Nic NetShim Network Consort MRCReflector PrefetchBuffer PrefetchListener

SUPPORTS_STANDALONE = false
SUPPORTS_SIMICS = true
DEFAULT_TARGET = simics
SUPPORTS_X86 = false
SUPPORTS_V9 = true
DEFAULT_PLATFORM = v9
