namespace Flexus {
namespace Dbg {

// clang-format off
char const * built_in_debug_cfg =
  "target \"debug-comp\" {                                                                                                                                                      "
  "  filter {                                                                                                                                                                     "
  "    - Stats ;                                                                                                                                                                  "
  "    - IterationCount ;                                                                                                                                                         "
  "    - Assert ;                                                                                                                                                                 "
  "    + Verb+ & {ComponentName} exists & {Message} exists;                                                                                                                       "
  "  }                                                                                                                                                                            "
  "  action {                                                                                                                                                                     "
  "    log console                                                                                                                                                                "
  "      {GlobalCount} \" <\" {File} \":\" {Line} \"> (\" {ComponentName} \"[\" {FlexusIdx} \"]) {\" {Cycles}  \"}- \" {Message} \"\\n\" ;                                        "
  "  }                                                                                                                                                                            "
  "}                                                                                                                                                                              "
  "target \"debug-feeder\" {                                                                                                                                                      "
  "  filter {                                                                                                                                                                     "
  "    - Stats ;                                                                                                                                                                  "
  "    - IterationCount ;                                                                                                                                                         "
  "    - Assert ;                                                                                                                                                                 "
  "    + Verb+ & Feeder ;                                                                                                                                                         "
  "  }                                                                                                                                                                            "
  "  action {                                                                                                                                                                     "
  "    log console                                                                                                                                                                "
  "      {GlobalCount} \" <\" {File} \":\" {Line} \"> (feeder[\" {FlexusIdx} \"]) {\" {Cycles}  \"}- \" {Message} \"\\n\" ;                                                       "
  "  }                                                                                                                                                                            "
  "}                                                                                                                                                                              "
  "target \"debug-noncomp\" {                                                                                                                                                     "
  "  filter {                                                                                                                                                                     "
  "    - Stats ;                                                                                                                                                                  "
  "    - IterationCount ;                                                                                                                                                         "
  "    - Assert ;                                                                                                                                                                 "
  "    - {ComponentName} exists ;                                                                                                                                                 "
  "    - Feeder ;                                                                                                                                                                 "
  "    + Verb+ & {Message} exists ;                                                                                                                                               "
  "  }                                                                                                                                                                            "
  "  action {                                                                                                                                                                     "
  "    log console                                                                                                                                                                "
  "      {GlobalCount} \" <\" {File} \":\" {Line} \"> {\" {Cycles}  \"}- \" {Message} \"\\n\" ;                                                                                   "
  "  }                                                                                                                                                                            "
  "}                                                                                                                                                                              "
  "target \"stats\" {                                                                                                                                                             "
  "  filter {                                                                                                                                                                     "
  "    + Stats ;                                                                                                                                                                  "
  "  }                                                                                                                                                                            "
  "  action {                                                                                                                                                                     "
  "    log console                                                                                                                                                                "
  "      {Source} \": \" {Message} \"\\n\" ;                                                                                                                                      "
  "  }                                                                                                                                                                            "
  "}                                                                                                                                                                              "
  "target \"assertions\" {                                                                                                                                                        "
  "  filter {                                                                                                                                                                     "
  "    + Assert ;                                                                                                                                                                 "
  "  }                                                                                                                                                                            "
  "  action {                                                                                                                                                                     "
  "    log console                                                                                                                                                                "
  "      {GlobalCount} \" <\" {File} \":\" {Line} \"> (\" {ComponentName} \"[\" {FlexusIdx} \"]) {\" {Cycles}  \"}- Assertion failed: (\" {Condition} \") : \" {Message} \"\\n\" ;"
  "    abort ;                                                                                                                                                                    "
  "  }                                                                                                                                                                            "
  "}                                                                                                                                                                              "
  ;
}
}
// clang-format on