
REQUIRED_COMPONENTS = Common BPWarm InorderSimicsFeeder MemoryLoopback MemoryMap MagicBreak IFetch Execute Cache

SUPPORTS_STANDALONE = false
SUPPORTS_SIMICS = true
DEFAULT_TARGET = simics
SUPPORTS_X86 = true
SUPPORTS_V9 = true
DEFAULT_PLATFORM = v9
