#ifndef FLEXUS__LAYOUT_IN_COMPONENT_DECLARATION
#error "Found end of component declaration without a corresponding begin"
#endif //FLEXUS__LAYOUT_IN_COMPONENT_DECLARATION

#undef FLEXUS__LAYOUT_IN_COMPONENT_DECLARATION

#undef COMPONENT_NO_PARAMETERS
#undef COMPONENT_PARAMETERS
#undef PARAMETER

#undef COMPONENT_INTERFACE
#undef PORT
#undef DRIVE

#undef FLEXUS_BEGIN_COMPONENT
#undef FLEXUS_END_COMPONENT

